services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: my-laravel-app:latest
    container_name: laravel_app
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:UgdvbTz7qY293wVOK5OieWDCP3/ggaFWOYzw/DFJqFE=
      APP_URL: http://localhost:59000
      
      # Database environment
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mode
      DB_USERNAME: appuser
      DB_PASSWORD: password
      
    volumes:
      - ./src:/var/www/html:delegated
      - /var/www/html/vendor
      - ./src/modules/User:/var/www/html/modules/User:ro
    depends_on:
      - mysql
    ports:
      - "9000:9000" # PHP-FPM listens on this port

  web:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "59000:80"
    command:

  mysql:
    image: mysql:8.0
    container_name: mode_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mode
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 5
      timeout: 5s
      start_period: 30s
      interval: 5s

volumes:
  mysql_data:
