services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: my-laravel-app:latest
    container_name: laravel_app
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:UgdvbTz7qY293wVOK5OieWDCP3/ggaFWOYzw/DFJqFE=
      APP_URL: http://localhost:59000
      
      # Database environment
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: appuser
      DB_PASSWORD: apppass
      
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/modules/User:/var/www/html/modules/User:ro
    depends_on:
      - mysql
    
    ports:
      - "59000:80"
    command: >
      sh -c "
      until php -r 'try { new PDO(\"mysql:host=mysql;dbname=app\", \"appuser\", \"apppass\"); } catch (Exception $e) { exit(1); }'; do
        echo 'Waiting for database connection...'; sleep 2;
      done;
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=80
      "

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 5
      timeout: 5s
      start_period: 30s
      interval: 5s

volumes:
  mysql_data:
